fink_topics:
  - fink_extragalactic_new_candidate_lsst
fink_username: testuser
fink_password: null
fink_group_id: group_id
survey: lsst # ztf or lsst
fink_servers: fink-broker-url
skyportal_token: token-to-replace
skyportal_url: http://localhost:5000
skyportal_group: Fink
testing: false
whitelisted: false
