name: skyportal-fink-client

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: skyportal
          POSTGRES_PASSWORD: anything
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a
        # healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        test_subset: ['Unit Testing of utils functions (with skyportal API)','Test Polling Alert']

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}

      - name: Write SkyPortal configs
        working-directory: ./skyportal
        run: |
          cat << EOF > config.yaml
            database:
              database: skyportal
              host: localhost
              port: 5432
              user: skyportal
              password: anything
          EOF
          cat << EOF > test_config.yaml
            database:
              database: skyportal_test
              user: skyportal
              host: localhost
              port: 5432
              password: anything
            server:
              auth:
                debug_login: True
          EOF
      - name: Install system dependencies
        working-directory: ./skyportal
        run: |
          curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash -
          sudo apt install -y wget nodejs unzip firefox nginx libcurl4-gnutls-dev libgnutls28-dev
          pip install pip==21.3.1
          pip install wheel numpy
          export NPM_PACKAGES="${HOME}/.npm-packages"
          export PATH=${NPM_PACKAGES}/bin:$PATH
          export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
          sudo npm -g install npm@latest
          which python; python --version
          echo npm $(npm --version)
          echo node $(node --version)
          nginx -v
          firefox --version

      - name: Initialize SkyPortal
        working-directory: ./skyportal
        run: |
          # Usually, we create databases on the local machine, so
          # `createdb` just works out of the box.  However, when doing
          # this on a server, as in our case, we need to specify extra
          # options.
          #
          # db_init should not complain if the databases exist already
          #
          echo "localhost:5432:*:skyportal:anything" > ~/.pgpass
          chmod 600 ~/.pgpass
          createdb -h localhost -U skyportal skyportal_test
          psql -U skyportal -h localhost -c "GRANT ALL PRIVILEGES ON DATABASE skyportal_test TO skyportal;" skyportal_test
          export NPM_CONFIG_LEGACY_PEER_DEPS="true"
          make db_init
          pip list --format=columns
          npm ls --depth 0 || true
          # Stamp Alembic HEAD
          PYTHONPATH=. alembic -x config=config.yaml stamp head

      - name: Refresh SkyPortal dependencies for tested version
        working-directory: ./skyportal
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          export NPM_CONFIG_LEGACY_PEER_DEPS="true"
          make dependencies

      - name: Install dependencies for skyportal-fink-client in a virtualenv
        run: |
          pip install virtualenv; virtualenv env; source env/bin/activate; pip install -r requirements.txt; deactivate

      - name: Run SkyPortal
        run: |
          PYTHONPATH=. python tests/run_skyportal.py

      - name: Get admin token from SkyPortal
        run: |
          source env/bin/activate
          py.test tests/test_skyportal_token.py

      - name: Unit testing of utils function with SkyPortal API
        if: ${{ matrix.test_subset == 'Unit Testing of utils functions (with skyportal API)' }}
        run: |
          source env/bin/activate
          py.test tests/test_skyportal_api.py

      - name: Generate Fake Alerts for testing
        if: ${{ matrix.test_subset == 'Test Polling Alert' }}
        run: |
          source env/bin/activate
          python tests/produce_fake.py

      - name: Test Poll Alerts using Fink Client and post it to SkyPortal
        if: ${{ matrix.test_subset == 'Test Polling Alert' }}
        run: |
          source env/bin/activate
          py.test tests/test_skyportal_fink_client.py

      - name: Test if the alerts posted to SkyPortal correspond to the fake alerts generated
        if: ${{ matrix.test_subset == 'Test Polling Alert' }}
        run: |
          source env/bin/activate
          py.test tests/test_confirmation.py

      - name: Stop SkyPortal
        working-directory: ./skyportal
        run: make stop
